version: '1.26'
services:
  mysql-docker:
    container_name:
      mysql
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: tpachato
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306
    restart: always


  app:
    container_name:
      angry_kalam
    depends_on:
      - mysql-docker
    build:
      context: .
    restart: always
    links:
      - mysql-docker
    ports:
      - 8082:8082
