version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: tpachato   
    ports:
      - 3306:3306
    networks:
     - AppNet
     
  spring-boot:
    image: amina123/springprojet
    container_name: spring
    ports:
      - 8082:8082
    depends_on:
      - database
    networks:
      - AppNet 
    restart: on-failure     
  angular:
    image:  amina123/front
    container_name: angular
    ports: 
      - 80:80
    depends_on:
      - spring-boot
    networks:
      - AppNet
  
networks:
  AppNet:
